// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHKORjAv-9ppLZ0dK_tYpQ7nonentkRd8',
    appId: '1:194338782167:android:b6a9dca2b10c529f07a992',
    messagingSenderId: '194338782167',
    projectId: 'stealthnote-mobile',
    storageBucket: 'stealthnote-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNowr4RKTLKAQNlElJIwb-DxAL1mHgXmE',
    appId: '1:194338782167:ios:737502664c77826f07a992',
    messagingSenderId: '194338782167',
    projectId: 'stealthnote-mobile',
    storageBucket: 'stealthnote-mobile.firebasestorage.app',
    androidClientId: '194338782167-r1n8prmmln1qbhktdktdsj81518nhtl8.apps.googleusercontent.com',
    iosClientId: '194338782167-aacck5o9nallmmoecroq46fu4uhrqir7.apps.googleusercontent.com',
    iosBundleId: 'org.pse.stealthnoteMobile',
  );

}